services:
  pokedex-diary:
    build:
      context: .
      dockerfile: Dockerfile
    image: thyrail/pokedex-diary:latest
    container_name: pokedex-diary
    ports:
      - "3120:80"
    restart: always